spring:
  profiles:
    active: 
     - default
     - database-default
     - logbook
     - mariadb-embedded
     - ports
     - security
  application:
    name: aaaserver

check-user-scopes: true
awaitTermination: 3000