spring:
  profiles:
    active: 
     - default
     - database-default
     - logbook
     - mariadb-embedded
     - ports
     - security
  application:
    name: aaaserver
  flyway:
    validate-on-migrate: false
    baseline-on-migrate: false
    ignore-missing-migrations: true
    
flyway:
  ignore-missing-migrations: true

check-user-scopes: true
awaitTermination: 3000
