spring:
  profiles:
    active: 
     - default
     - database-default
     - logbook
     - mariadb-embedded
     - ports
     - security
  application:
    name: aaaserver
  flyway:
    validate-on-migrate: true
    baseline-on-migrate: true

check-user-scopes: true
awaitTermination: 3000
